### ISSUE TITLE
Ranged ammo dissapears

### ISSUE THREAD

**Issue by Paniskio** [R-Vaccari/bannerlord-banner-kings#136]
After changing from 1.2.7.3 to 1.2.7.4 the following has been happening:
Wood naturally just disappears from my inventory with not reason to why this is happening.
![20230605113827_1](https://github.com/R-Vaccari/bannerlord-banner-kings/assets/135598696/8176abb2-e767-4f4a-9716-619e8edd80f1)
![20230605114210_1](https://github.com/R-Vaccari/bannerlord-banner-kings/assets/135598696/d48400d8-6bb9-4964-9495-d605cb4988ca)
![20230605114426_1](https://github.com/R-Vaccari/bannerlord-banner-kings/assets/135598696/501da5cd-2627-46d8-87c4-8a11329cdc05)

My arrows and bolts for my ranged weapons will disappear at what seems to be random moments, even if locked.

I have tried to roll back to 1.2.7.2 and this appears to not be an issue on that version, at least of what I have observed.

**Comment by Marcolino748** [comment]
I am having the same issue with Melee Weapons  (swords and lances) . It is making the game unplayable. I had a total of 50 swords and axes in my inventory (to test it). In less than two game days, where my character's party was not in any settlement but standing immobile outside, some of the devices simply vanished. Within less than two days my 50 weapons went down to 32.

**Comment by R-Vaccari** [comment]
Download description: "Read Changelog"
1.2.7.4 changelog: "Added Party Supplies feature"
1.2.7.4-1 changelog: "Added Wiki documentation about supplies and other features at Github"

**Comment by Marcolino748** [comment]
Thanks. I had not realised the Party Supply feature. It certainly make sit more realistic. But, could I ask a couple of questions?
1. Is it possible to not have the party consume a weapon that is in the inventory but is locked ?
2. The wiki mentions that we can talk to the quartermaster to have them purchase the required equipment/supplies. However, how is it done when the player is also the quartermaster?
Thanks and sorry for these questions

**Comment by R-Vaccari** [comment]
There's a MCM setting to disable the supply needs rate. If you're the quartermaster you have to do it yourself.

**Comment by Marcolino748** [comment]
Thank you

**Comment by AuntJemima1** [comment]
I have the supply needs setting set to zero and tools are still disappearing is there something else I have to do? I tried talking to my quartermaster but I didn't see any different dialogue options

**Comment by Sozzky** [comment]
This really needs to be changed to either not use locked items or an option in the mod settings to completely remove deleting weapons for it. Makes smithing training extremely annoying, as all the weapons/wood/charcoal I buy to train with just get deleted whenever I need to regain crafting stamina.
