### ISSUE TITLE
Features para Lançamento

### ISSUE THREAD

**Issue by R-Vaccari** [R-Vaccari/bannerlord-banner-kings#2]
Coisas a se fazer antes da publicação.

- Notificações de mapa (opcional): Já vi como lançar a notificação, porém requer um registro da classe difícil de entender (autogerado no nativo).

1. Novos stats: Implementar novos stats associados à posse de títulos, como número máximo de vassalos.
- - [ ] Definir stats. Número de vassalos pode ser influenciado por nível de clã, nível do título mais alto, e tipo de governo;

2. Direitos & Deveres: Implementar os impactos de direitos e deveres.
- - [ ] Cobrança de impostos (quase pronto em modelo de finanças de clã);
- - [ ]  Jogador ter de presenciar exércitos quando chamado;
- - [ ] Alguma forma de burlar eleições para direito de conquista e direito absoluto (conquistar sozinho vs já ter o título da terra);

3. Formas de Herança: Implementar diferentes formas de definir quem herda o clã após a morte do líder.
- - [ ] Primogenitura: Filho(a) mais velho capaz de herdar;
- - [ ] Ultimogenitura: Filho(a) mais novo capaz de herdar (a partir de adolescente);
- - [ ] Senioridade: Membro mais velho do clã, independente de sangue.

4. Leis de Gênero: Implementar diferentes formas de definir quem herda o clã após a morte do líder.
- - [ ] Agnática: Preferência masculina;
- - [ ] Cognática: Mulheres herdam igualmente.

5. Formas de Sucessão: Implementar diferentes formas de definir o clã que herda a facção. Tudo / maioria pode ser feito em KillCharacterAction.
- - [ ] Monarquia Hereditária: O líder da facção sempre será o próximo líder do clã soberano, independente da forma de herança;
- - [ ] Monarquia Eletiva (High Kingship): Sucessão padrão;
- - [ ] Sucessão Republicana (se possível implementar república): Preferência por líderes mais velhos e de famílias de prestígio;
- - [ ] Sucessão Imperial: Imperador escolhe o sucessor.

6. Formas de Governo: A forma de governo é independente da forma de sucessão e outras leis. Porém, pode mudar as opções disponíveis. Cada governo teria seus efeitos passivos (traits, como culturas).
- - [ ] Feudal: Focado na distribuição de poder e posse legal da terra. Bônus em produtividade;
- - [ ] Tribal: Focado em combate e glória. Bônus associados a conquista;
- - [ ] Imperial: Concentra poder. Decisões do imperador têm mais peso que opiniões de lordes. Prestigioso.
- - [ ] República: Focado no apelo popular (stability). Eleições anuais (aqui a dificuldade em implementar).

**Comment by carrascodev** [comment]
Tem alguma dessas features que estão prontas/parcialmente prontas ou em progresso?

**Comment by R-Vaccari** [comment]
Só a cobrança de impostos está quase pronta. O resto tenho noção de como implementar.
