### ISSUE TITLE
Village Income Bug When Usurping Title

### ISSUE THREAD

**Issue by Hazerre** [R-Vaccari/bannerlord-banner-kings#33]
I was experiencing a repeatable bug where I had established my own kingdom by taking a castle. After the peace I tried to usurp the titles to avoid 0% stability. When I usurped the title for a village, but not the corresponding castle, I would stop receiving income from that village until I also acquired the title for the castle.

**Comment by R-Vaccari** [comment]
Sorry for the delay, at the time I didn't check github for issues. The village income logic was completely remade and so I doubt this is an issue still.
