### ISSUE TITLE
Cultural Assimilation Loyalty will never progress with different culture Clans and Kingdom

### ISSUE THREAD

**Issue by ApoxPaito** [R-Vaccari/bannerlord-banner-kings#35]
To be more specific with this, Clans that aren't the same culture with the Kingdom they are in will never get positive modifiers from assimilation of the settlements they have been assigned with. "How?" you might ask, because
```csharp
//BKLoyaltyModel.cs, line 142 on repo by the time I've submitted this issue
float assim = data.CultureData.GetAssimilation(town.Owner.Culture); //town.Owner points to the party owning the settlement, not the actual Hero who owns the town
//PopulationData.cs, line 413 on repo by the time I've submitted this issue
if (cultureData.Culture != settlementOwner.Culture && cultureData.Assimilation > 0.01)
   toDelete.Add(cultureData);
```
This means that if the dominant culture ever goes over 1% assimilation AND the clan owning the settlement doesn't have the same culture as the dominant culture, the culture will simply get snapped away. Combine this with the fact that the Faction culture is factored into Cultural Assimilation, and you will have -4 Cultural Assimilation (if you are lucky maybe something lower than -3.6) because there is no Culture in the settlement that can provide a high Assimilation modifier. This is also a big problem if you convert a settlement and then give it away to one of your different culture vassals, as they will immediately cause the CultureData to be deleted and you will get a constant penalty ranging around -4 and -3.6. Now I dunno how this is supposed to be fixed or if it is intended, but I guess this is a nice heads-up.

P.S. Also from what I can gather, anyone but the player character will add their culture to a settlement. This means that there is no real assimilation going on on a newly conquered settlement by other lords.
```csharp
//PopulationData.cs, line 342
public Hero SettlementOwner
{
    get => this.settlementOwner;
    set
    {
        this.settlementOwner = value;
        if (!this.IsCulturePresent(settlementOwner.Culture) && settlementOwner == Hero.MainHero)
        {
            if (this.settlementOwner.Culture == this.DominantCulture)
                this.AddCulture(settlementOwner.Culture, 1f, 1f);
            else this.AddCulture(settlementOwner.Culture, 0f);
        }
    }
}
```

**Comment by ApoxPaito** [comment]
Oh yikes, not only Loyalty but the Security too.
```csharp
// BKSecurityModel.cs, line 27
float assim = data.CultureData.GetAssimilation(town.Owner.Culture);
```

**Comment by R-Vaccari** [comment]
Thanks, I will check these for next update. Mostly busy with religions in dev.

**Comment by R-Vaccari** [comment]
Thanks for pointing these out. `cultureData.Assimilation > 0.01` should really be `cultureData.Assimilation < 0.01`, so cultures that are not owner's and have very little assimilation go away. Classical operator mistake.
The second thing is more of a bandaid as somehow it was happening to a few players. But I'll remove the mainhero constraint regardless. In most cases the culture is present and so assimilation works normally for player and AI.
