### ISSUE TITLE
Crash on MenuEstatesManageCondition

### ISSUE THREAD

**Issue by brandonm4** [R-Vaccari/bannerlord-banner-kings#55]
My Fix:

private static bool MenuEstatesManageCondition(MenuCallbackArgs args)
        {
            args.optionLeaveType = GameMenuOption.LeaveType.RansomAndBribe;
            if (Settlement.CurrentSettlement != null)  // <--Added null check
            {
                var settlement = Settlement.CurrentSettlement;
                var data = BannerKingsConfig.Instance.PopulationManager.GetPopData(settlement);
                return data.EstateData != null;
            }
            return false;
        }

**Comment by brandonm4** [comment]
Actually that did not fix it.
I put a try / catch around the whole method and that stopped the crash.  Maybe the args.optionLeaveType is coming in as null?

**Comment by R-Vaccari** [comment]
I fixed it, thank you.
