### ISSUE TITLE
EncyclopediaHeroPageMixin compatibility issue

### ISSUE THREAD

**Issue by artifixer** [R-Vaccari/bannerlord-banner-kings#59]
Hi!
[EncyclopediaHeroPageMixin](https://github.com/R-Vaccari/bannerlord-banner-kings/blob/main/BannerKings/UI/Extensions/EncyclopediaHeroPageMixin.cs#L48) has a compatibility issue with any other mod that also changes this page. As long as Banner Kings is not the only one or the last loaded mod that changes the EncyclopediaHeroPage, `OnRefresh()` method will be called multiple times.
Due to the fact that it unconditionally clears the base view model stats, but refills them only ones, that leads to the empty stat screen:
```csharp
            heroPageVM.Stats.Clear();
            Marriage.Clear();
            Hero hero = (Hero)heroPageVM.Obj;

            if (!addedFields)
            ( . . .)
```

**Comment by R-Vaccari** [comment]
Thanks, will look into a solution.

**Comment by AllFater888** [comment]
Any fix ?

**Comment by EdmundNasher** [comment]
Hi Lads,

Any update if this will get fixed?

Thanks

**Comment by artifixer** [comment]
> Maybe a toggle on-off button for encyclopedia editor so people can turn that part off which causes compatibility issues.

It would be easier to just fix the issue.

**Comment by EdmundNasher** [comment]
> > Maybe a toggle on-off button for encyclopedia editor so people can turn that part off which causes compatibility issues.
> 
> It would be easier to just fix the issue.

True but this has been open for far too long so maybe not something that can easily be fixed.

I assume there is nothing that can be done from your end at Diplomacy side?

**Comment by artifixer** [comment]
> not something that can easily be fixed.
It absolutely **can** be easily fixed. For example, shifting the top three lines down in an "if" statement barely takes more than a minute. Why would you unconditionally clear all the stats, but fill them only once? You should do those operations together - either clearing and filling every time or doing it once, as I'd suggest.

> I assume there is nothing that can be done from your end at Diplomacy side?
I can manually re-fill the stats if they are empty, but why should DIplomacy do this if it does not touch the stats in the first place?

**Comment by EdmundNasher** [comment]
> > not something that can easily be fixed.
> 
> It absolutely **can** be easily fixed. For example, shifting the top three lines down in an "if" statement barely takes more than a minute. Why would you unconditionally clear all the stats, but fill them only once? You should do those operations together - either clearing and filling every time, or do both just once, as I would suggest.
> 
> > I assume there is nothing that can be done from your end at Diplomacy side?
> 
> I can manually re-fill the stats if they are empty, but why should DIplomacy do this if it does not touch the stats in the first place? Diplomacy only alters that page to add a "Send Messenger" button.

Fair point

**Comment by laryakan** [comment]
Related issue : https://github.com/R-Vaccari/bannerlord-banner-kings/issues/63

**Comment by KodiSky** [comment]
> Hi! [EncyclopediaHeroPageMixin](https://github.com/R-Vaccari/bannerlord-banner-kings/blob/main/BannerKings/UI/Extensions/EncyclopediaHeroPageMixin.cs#L48) has a compatibility issue with any other mod that also changes this page. As long as Banner Kings is not the only one or the last loaded mod that changes the EncyclopediaHeroPage, `OnRefresh()` method will be called multiple times. Due to the fact that it unconditionally clears the base view model stats, but refills them only ones, that leads to the empty stat screen:
> 
> ```cs
>             heroPageVM.Stats.Clear();
>             Marriage.Clear();
>             Hero hero = (Hero)heroPageVM.Obj;
> 
>             if (!addedFields)
>             ( . . .)
> ```

Ive been trying to implement this my self but I cant find all the dependencies I need to recompile BK properly. Maybe if you know how to do it, you could make a pull request so everyone can lay it to rest?

**Comment by EdmundNasher** [comment]
This is fixed now.
