### ISSUE TITLE
Add assets install location to readme

### ISSUE THREAD

**Issue by Hornsoup** [R-Vaccari/bannerlord-banner-kings#61]
The installation guide is too quiet I had to really work to hear it, and I'm sure a number of people have the same question that should be answered in the readme: Where do the assets go, in the mod folder or overwriting the base install? I'm assuming the folder but it's quite unclear. Also I don't see the assets in the Deployment folder so it's confusing as to where they're even kept -_-;;

**Comment by jadusf** [comment]
doesnt it say that drop the assets in the BK folder ?

**Comment by Hornsoup** [comment]
If "it" is the vid, I reviewed it and the maker's just guessing so it's
still ambiguous. If you mean something else then you'll have to avoid
pronouns and define what "it" is. The act of adding clear and obvious
written instruction is such a simple step, please consider writing a single
line in to avoid ambiguity.

**Comment by bnn1** [comment]
@Hornsoup nexus' mod page clearly states to extract contents of assets into bannerlord/modules/bannerkings folder
>Extract contents into Bannerlord folder/Modules/BannerKings.

**Comment by Hornsoup** [comment]
At the time of writing to my memory this added indication was not there
stating only the Bannerlord folder. Either way it's fixed.

**Comment by R-Vaccari** [comment]
It was always there, and the main description has a link to a full guide on youtube made by a player.
