### ISSUE TITLE
A problem about smithing

### ISSUE THREAD

**Issue by zzy1261063321** [R-Vaccari/bannerlord-banner-kings#68]
**Describe the bug**
If you let you companion to forge, craft or refine. They can finish the work instantly. For example, it will take myself 1.0 hour to use 2 Haedwood to create 1 Charcoal, but it only take my wife 0.0 hour to finish this work, which means you can get the Charcoal immediately instead of waiting a hour. Both of us have 0 smithing skill level
**Mod Version**
- Standard version
- Numeric Version: 1.2.6.1

**Comment by R-Vaccari** [comment]
It's currently intended.
