### ISSUE TITLE
Game crashes when clicking on demesne hierarchy in town menu

### ISSUE THREAD

**Issue by abhowitzer** [R-Vaccari/bannerlord-banner-kings#70]
**Describe the bug**
Game crashes when clicking on any options in the Banner Kings menu.
Weird thing is that the banner king menu does not show up UNLESS I craft something.

**Mod Version**
- Standard version
- Numeric Version: 1.2.6.1

**Evidence**
- [x] The mod is present in the callstack;
- [x] The issue only happens with the mod activated;
- [x] You tested it with the least amount of other mods as possible.

**Crash Reports**
https://report.butr.link/270721.html (clicking on demesne hierarchy)
https://report.butr.link/3F5D7C.html (clicking on demesne management)

Exact moment where the crash happened:
![image](https://user-images.githubusercontent.com/29637532/216613407-acd7ad99-aebc-4c11-a490-34d7e1cdb91e.png)

**Comment by R-Vaccari** [comment]
This seems to be related to a bug in 1.2.6.1 that caused inconsistency with the mod data. Menu option missing indicates that. There's no around it other than starting a campaign with an updated version. It's in the changelog of 1.2.6.5.
